[project]
name = "langchain-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "dotenv>=0.9.9",
    "langchain-openai>=0.3.19",
    "langchain[anthropic,openai]>=0.3.25",
]
